# Generated by Django 4.1.6 on 2023-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astral',
            fields=[
                ('astral_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('created_by', models.CharField(default=None, max_length=200)),
                ('ultraviolet_filter', models.CharField(max_length=30)),
                ('green_filter', models.CharField(max_length=30)),
                ('near_infrared_filter', models.CharField(max_length=30)),
                ('red_filter', models.CharField(max_length=30)),
                ('infrared_filter', models.CharField(max_length=30)),
                ('modified_julian_date', models.CharField(max_length=30)),
                ('spectroscopic_objects_id', models.CharField(max_length=30)),
                ('redshift_value', models.CharField(max_length=30)),
                ('plate_id', models.CharField(max_length=30)),
            ],
        ),
    ]
