# Generated by Django 4.1.6 on 2023-02-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstralObject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astral',
            name='astral_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
